### ISSUE TITLE
Blurry logo on HiDPI display (use SVG over PNG logo images)

### ISSUE THREAD

**Issue by paulmenzel** [zitadel/.github#4]
The README logo’s on GitHub are blurry on a HiDPI display. It looks like SVG versions [exist][1].

[1]: https://zitadel.com/zitadel-logo-dark.svg

**Comment by fforootd** [comment]
Haha fair, I was not aware that GH supports[ this officially](https://github.blog/changelog/2022-01-21-allow-to-upload-svg-files-to-markdown/). 

I will do a PR for this later.
